
site_name: Tracs - Documentation
site_url: https://github.com/fortysix2ahead/tracs

nav:
    - Home: index.md
    - Getting Started: start.md
    - Activities: activities.md
    - Resources: resources.md
    - Filters: filters.md
    - Command Line Interface: cli.md
    - Plugins: plugins.md
    - Bikecitizens: bikecitizens.md
    - Local: local.md
    - Polar: polar.md
    - Strava: strava.md
    - Waze: waze.md
    - Internals: internals.md

# theme: readthedocs
theme: material
markdown_extensions:
    - mkdocs-click
