
# main keys, values can partially be overwritten via command line arguments

debug: no # enables debug mode
force: no # enable force mode, which does not ask any questions
library: # absolute path to the activity library
pretend: no # pretend mode, simulates all commands, but does not persist changes
verbose: no # verbose mode, displays more log information

# database configuration

db:
  index: no

# configuration for printing activity/resource information

formats:
  locale: 'en'
  date: medium # allowed values: short, medium, long, full
  datetime: medium # allowed values: short, medium, long, full
  time: medium # allowed values: short, medium, long, full
  timedelta: short  # allowed values: narrow, short, long
  list:
    default: id name type starttime_local uids
  show:
    default: id name type starttime_local timezone duration distance
    all:

# experimental: allow predefined filters

filters:
  default:

import:
  range: 90 # number of days to fetch activities from (today to -90 days), lowering will speed up import command
  first_year: 2000 # year to start from when fetching all activities, most likely there's nothing before 2000

# gpx parser configuration

gpx:
  parser: gpxpy # allowed values: internal, gpxpy, currently ignored

pluginpath: # list of additional plugin paths, separated by whitespace
