
plugins:

  bikecitizens:
    last_fetch:
    last_download:

  polar:
    last_fetch:
    last_download:

  strava:
    access_token:
    refresh_token:
    expires_at:
    last_fetch:
    last_download:

  waze:
    fetch:         # we can probably remove this field once support of last_fetch is implemented
      takeouts:
    last_fetch:
    last_download:
